### ISSUE TITLE
Specs satisfying the `TXIMSDK_Plus_iOS (= 6.6.3002), TXIMSDK_Plus_iOS (= 7.1.3925), TXIMSDK_Plus_iOS (= 6.9.3557)` dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by shitaBro** [hellohejinyu/tencent_chat_push_for_china#1]
CocoaPods could not find compatible versions for pod "TXIMSDK_Plus_iOS":
  In snapshot (Podfile.lock):
    TXIMSDK_Plus_iOS (= 6.6.3002)

  In Podfile:
    tencent_cloud_chat_sdk (from `.symlinks/plugins/tencent_cloud_chat_sdk/ios`) was resolved to 5.1.2, which depends on
      TXIMSDK_Plus_iOS (= 7.1.3925)

    tencent_im_sdk_plugin (from `.symlinks/plugins/tencent_im_sdk_plugin/ios`) was resolved to 5.0.4, which depends on
      TXIMSDK_Plus_iOS (= 6.9.3557)

Specs satisfying the `TXIMSDK_Plus_iOS (= 6.6.3002), TXIMSDK_Plus_iOS (= 7.1.3925), TXIMSDK_Plus_iOS (= 6.9.3557)` dependency were found, but they required a higher minimum deployment target.

**_flutter yaml_**
tencent_chat_push_for_china: ^2.6.0
tencent_im_sdk_plugin: ^5.0.5

**Comment by hellohejinyu** [comment]
老哥，这是我自己从 pub.dev 上面扒下来然后二开适配我们自己项目用的。腾讯云那边没有放他们的 GitHub 仓库。建议你去咨询腾讯云。

**Comment by shitaBro** [comment]
ok
